---
title: "blah blah blah"
description: |
  blah blah blah blah
author: Minsong Kim
date: October 25, 2025
format: 
  html:
    code-fold: true
    code-summary: "Code"
---

```{r}
#| include: false
library(tidyverse)
library(ggplot2)
library(tictoc)
```

maybe that one math question, where you are given 3 doors, behind one of the door is a car. you select one, and one of the other doors is shown to be a dud. do you switch?

```{r}
monty_hall <- function(switch_choice) {
  doors <- letters[1:3] 
  first_choice <- sample(doors, 1)
  
  
  reveal <- if (first_choice == "a") {
    sample(doors[doors != "a"], 1)
  } else if (first_choice == "b") {
    "c"
  } else {
    "b"
  }
  
  doors <- doors[doors != reveal]
  
  second_choice = if (switch_choice == 1) {
    second_choice = sample(doors[doors != first_choice], 1)
  } else {
    second_choice = first_choice
  }

  result = ifelse(second_choice == "a",
                         "Sucess!",
                         "Dud..."
                  )
  data.frame(second_choice, result)
}

n <- 100000
tic()
switch_result <- 1:n |>
  map(~ monty_hall(1)) |>
  list_rbind()
toc()

switch_result |>
  group_by(result) |>
  summarise(number = n()) |>
  mutate(proportion = number / sum(number))

tic()
noswitch_result <- 1:n |>
  map(~ monty_hall(0)) |>
  list_rbind()
toc()

noswitch_result |>
  group_by(result) |>
  summarise(number2 = n()) |>
  mutate(proportion2 = number2 / sum(number2))
```

```{r}


ggplot
```
